import React, { useMemo } from 'react';

function cleanLine(raw) {
  if (raw == null) return '';
  return String(raw)
    .replace(/^[│\s]+/, '')
    .replace(/[│\s]+$/, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function isDivider(line) {
  const t = line.trim();
  return /^[═─]{4,}$/.test(t) || /^[\s│]*[─]{8,}[\s│]*$/.test(line);
}

function parseStageHeader(line) {
  const t = cleanLine(line);
  const m = t.match(/^STAGE\s+(\d+)\s*(?:[─\-–—]+\s*)?(.+)?$/i);
  if (!m) return null;
  const num = parseInt(m[1], 10);
  const rest = (m[2] || '').replace(/^[─\-–—]+\s*/, '').trim();
  return { num, title: rest ? `STAGE ${num} — ${rest}` : `STAGE ${num}` };
}

function extractField(lines, field) {
  const re = new RegExp(`^${field}\\s*:`, 'i');
  for (const line of lines) {
    if (re.test(line)) return line.split(':').slice(1).join(':').trim();
  }
  return '';
}

/** Turn ASCII box lines into one conversational formula string. */
function boxToFormulaMessage(lines) {
  const cleaned = lines.map(cleanLine).filter(Boolean);
  if (!cleaned.length) return null;

  const first = cleaned[0];
  let label = '';
  if (/MIXTURE\s+[A-D]/i.test(first)) {
    label = first.match(/MIXTURE\s+[A-D]/i)[0].toUpperCase();
  } else if (/OIL\s+FORMULA/i.test(first)) {
    label = 'OIL FORMULA';
  } else if (/MIXTURE\s+D/i.test(first)) {
    label = 'MIXTURE D';
  }

  const formula = extractField(cleaned, 'Formula');
  const timing = extractField(cleaned, 'Timing');
  const dose = extractField(cleaned, 'Dose');
  const frequency = extractField(cleaned, 'Frequency');
  const method = extractField(cleaned, 'Method');
  const water = extractField(cleaned, 'Water');
  const apply = extractField(cleaned, 'Apply on') || extractField(cleaned, 'Apply');

  let context = first
    .replace(/^MIXTURE\s+[A-D]\s*[─\-–—]\s*/i, '')
    .replace(/^OIL\s+FORMULA\s*[─\-–—]\s*/i, '')
    .replace(/\s{2,}Oral\s*│.*/i, '')
    .replace(/\s{2,}Globules\s*│.*/i, '')
    .replace(/\s{2,}External\s*│.*/i, '')
    .trim();

  const oralMatch = first.match(/Oral\s*│\s*(D\d+)/i);
  const globMatch = first.match(/Globules\s*│\s*(D\d+)/i);
  const extMatch = first.match(/External\s*│\s*(D\d+)/i);
  const potency = oralMatch?.[1] || globMatch?.[1] || extMatch?.[1] || '';
  if (potency && !context.includes(potency)) {
    context = context ? `${context} ${potency}` : potency;
  }

  const details = [timing, dose, frequency, method, water, apply].filter(Boolean);

  const narrative = cleaned
    .filter(
      (l) =>
        !/^(Formula|Timing|Dose|Frequency|Method|Water|Apply|Note)\s*:/i.test(l) &&
        !/^MIXTURE|^OIL FORMULA/i.test(l) &&
        !/^─+$/.test(l) &&
        !/^Active Symptom/i.test(l)
    )
    .filter((l) => l.length > 20);

  if (!label) {
    return null;
  }

  return {
    type: 'formula',
    label: label || 'Prescription',
    context,
    formula,
    details,
    narrative: narrative.slice(0, 4),
  };
}

function classifyLine(text) {
  const t = text || '';
  if (!t) return null;

  if (t.includes('EH AROGYA SUTRA') && /CLINICAL|PRESCRIPTION/i.test(t)) {
    return { type: 'system', text: t, variant: 'brand' };
  }

  if (/^(Patient|Date|BP|Systems|Ref)\s*:/i.test(t)) {
    return { type: 'meta', text: t };
  }

  if (/^(Temperament|Polarity|Potency|Safety Status|Next Appointment)\s*:/i.test(t)) {
    return { type: 'highlight', text: t };
  }

  if (/^(MORNING|AFTERNOON|EVENING|NIGHT|BEDTIME)/i.test(t)) {
    return { type: 'schedule', text: t };
  }

  if (t.startsWith('⚠') || t.startsWith('IMPORTANT') || /GOLDEN RULE|AGGRAVATION|ELEVATED/i.test(t)) {
    return { type: 'warning', text: t };
  }

  if (t.startsWith('✓') || t.startsWith('✗')) {
    return { type: 'diet', text: t };
  }

  if (/^Rule\s+\d+/i.test(t)) {
    return { type: 'rule', text: t };
  }

  if (/INTEGRATION|VERIFICATION/i.test(t) && t.length < 80) {
    return { type: 'subheading', text: t };
  }

  return { type: 'text', text: t };
}

function parseSummaryToMessages(summary) {
  if (!summary?.trim()) return [];

  const messages = [];
  let inBox = false;
  let boxLines = [];
  let inFooter = false;

  const flushBox = () => {
    if (!boxLines.length) return;
    const formula = boxToFormulaMessage(boxLines);
    if (formula) {
      messages.push(formula);
    } else {
      const text = boxLines.map(cleanLine).filter(Boolean).join(' · ');
      if (text) messages.push({ type: 'bubble', variant: 'info', text });
    }
    boxLines = [];
    inBox = false;
  };

  const pushText = (line) => {
    const cleaned = cleanLine(line);
    if (!cleaned || isDivider(line)) return;

    if (/^Generated by EH Arogya Sutra/i.test(cleaned)) {
      inFooter = true;
      messages.push({ type: 'footer', text: cleaned });
      return;
    }
    if (inFooter) {
      messages.push({ type: 'footer', text: cleaned });
      return;
    }

    if (cleaned.includes('┌') || cleaned.includes('├')) {
      inBox = true;
      return;
    }
    if (inBox) {
      if (cleaned.includes('└')) {
        flushBox();
        return;
      }
      boxLines.push(cleaned);
      return;
    }

    const stage = parseStageHeader(cleaned);
    if (stage) {
      messages.push({ type: 'stage', title: stage.title });
      return;
    }

    const msg = classifyLine(cleaned);
    if (msg) messages.push(msg);
  };

  for (const raw of summary.split('\n')) {
    pushText(raw);
  }
  flushBox();

  return messages;
}

function StageDivider({ title }) {
  return (
    <div className="flex w-full items-center gap-3 py-2 md:py-3">
      <div className="h-px flex-1 bg-[#c9963a]/20" />
      <span className="shrink-0 px-2 text-center font-serif text-[11px] font-bold uppercase leading-snug tracking-wide text-[#e8c46a]/90 md:text-xs">
        {title}
      </span>
      <div className="h-px flex-1 bg-[#c9963a]/20" />
    </div>
  );
}

function ChatBubble({ children, variant = 'default', className = '' }) {
  const styles = {
    default: 'bg-[#0f1f10]/95 border-white/10',
    formula: 'bg-[#4a9b54]/08 border-[#4a9b54]/25',
    meta: 'bg-[#c9963a]/06 border-[#c9963a]/18',
    warning: 'bg-orange-500/08 border-orange-500/25',
    schedule: 'bg-[#0b1a0d] border-[#c9963a]/15',
    diet: 'bg-[#0f1f10]/80 border-white/8',
    brand: 'bg-gradient-to-br from-[#0f1f10] to-[#080f09] border-[#c9963a]/25',
  };

  return (
    <div
      className={`w-full rounded-2xl rounded-tl-md border px-4 py-3.5 shadow-sm shadow-black/20 md:rounded-3xl md:px-5 md:py-4 ${styles[variant] || styles.default} ${className}`}
    >
      {children}
    </div>
  );
}

function MessageRow({ message }) {
  switch (message.type) {
    case 'stage':
      return <StageDivider title={message.title} />;

    case 'formula':
      return (
        <ChatBubble variant="formula">
          <p className="text-sm leading-relaxed text-white/92 md:text-[15px] md:leading-relaxed">
            <span className="font-bold text-[#6abf72]">{message.label}</span>
            {message.context ? <span className="text-white/90"> — {message.context}</span> : null}
            {message.formula ? (
              <span className="text-white/85"> (Formula: {message.formula})</span>
            ) : null}
          </p>
          {message.details.length > 0 && (
            <p className="mt-2.5 text-xs leading-relaxed text-white/55 md:text-sm">
              {message.details.join(' · ')}
            </p>
          )}
          {message.narrative?.map((line, i) => (
            <p key={i} className="mt-2 text-xs leading-relaxed text-white/45 md:text-sm">
              {line}
            </p>
          ))}
        </ChatBubble>
      );

    case 'meta':
      return (
        <ChatBubble variant="meta">
          <p className="text-sm leading-relaxed text-white/85 md:text-[15px]">{message.text}</p>
        </ChatBubble>
      );

    case 'highlight':
      return (
        <ChatBubble variant="meta">
          <p className="text-sm font-medium leading-relaxed text-[#e8c46a] md:text-[15px]">{message.text}</p>
        </ChatBubble>
      );

    case 'schedule': {
      const parts = message.text.split('→').map((s) => s.trim());
      return (
        <ChatBubble variant="schedule">
          <p className="text-sm leading-relaxed text-white/90 md:text-[15px]">
            <span className="font-bold uppercase tracking-wide text-[#e8c46a]">{parts[0]}</span>
            {parts[1] ? (
              <>
                <span className="mx-2 text-[#4a9b54]">→</span>
                <span>{parts[1]}</span>
              </>
            ) : null}
          </p>
        </ChatBubble>
      );
    }

    case 'warning':
      return (
        <ChatBubble variant="warning">
          <p className="text-sm leading-relaxed text-orange-200/95 md:text-[15px]">{message.text}</p>
        </ChatBubble>
      );

    case 'diet':
      return (
        <ChatBubble variant="diet">
          <p
            className={`text-sm leading-relaxed md:text-[15px] ${message.text.startsWith('✓') ? 'text-[#6abf72]' : 'text-red-400'}`}
          >
            {message.text}
          </p>
        </ChatBubble>
      );

    case 'subheading':
      return (
        <p className="w-full px-1 py-1 text-[11px] font-bold uppercase tracking-widest text-white/40 md:text-xs">
          {message.text}
        </p>
      );

    case 'rule':
      return (
        <ChatBubble variant="default">
          <p className="font-mono text-xs leading-relaxed text-white/55 md:text-sm">{message.text}</p>
        </ChatBubble>
      );

    case 'system':
      return (
        <ChatBubble variant="brand">
          <p className="text-center font-serif text-sm font-bold uppercase tracking-[0.2em] text-[#e8c46a] md:text-base">
            {message.text}
          </p>
        </ChatBubble>
      );

    case 'footer':
      return (
        <p className="w-full py-2 text-center text-[10px] uppercase tracking-widest text-white/25 md:text-xs">
          {message.text}
        </p>
      );

    case 'bubble':
      return (
        <ChatBubble variant={message.variant === 'info' ? 'default' : message.variant}>
          <p className="text-sm leading-relaxed text-white/75 md:text-[15px]">{message.text}</p>
        </ChatBubble>
      );

    case 'text':
    default:
      if (!message.text?.trim()) return null;
      return (
        <ChatBubble variant="default">
          <p className="text-sm leading-relaxed text-white/70 md:text-[15px]">{message.text}</p>
        </ChatBubble>
      );
  }
}

export default function ClinicalSummaryDisplay({ summary }) {
  const messages = useMemo(() => parseSummaryToMessages(summary), [summary]);

  if (!summary?.trim() || !messages.length) return null;

  return (
    <div className="flex w-full flex-col gap-3 md:gap-4">
      {messages.map((msg, i) => (
        <MessageRow key={`${msg.type}-${i}`} message={msg} />
      ))}
    </div>
  );
}
