/** Frozen Q7B-F minimum preconditions (Phase 5R-4D-Q07B-F) — explicit gate ledger for Phase 8 D3/D5. */
export const RULE4_Q7BF_MANDATORY_GATE_IDS = [
  'Q7BF_RULE3_TARGET_RESOLVED',
  'Q7BF_FORMULA_SPECIFIC_PATHOLOGY',
  'Q7BF_POSITIVE_DISEASE_POLARITY',
  'Q7BF_NEGATIVE_THERAPEUTIC_POLARITY',
  'Q7BF_ACUTE_PHASE',
  'Q7BF_CLOSE_D04_USABLE_EVIDENCE',
  'Q7BF_STRICT_FORMULA_ISOLATION',
  'Q7BF_NO_GLOBAL_EVIDENCE_LEAKAGE',
] as const;

export type Rule4Q7bfMandatoryGateId = (typeof RULE4_Q7BF_MANDATORY_GATE_IDS)[number];

export const RULE4_Q7BF_MANDATORY_GATE_ID_SET = new Set<string>(RULE4_Q7BF_MANDATORY_GATE_IDS);
