/** Owner-approved clinical R5_* identifiers (OD-R5-M0-014 + OD-R5-M0-015). Metadata-only in R5-M2. */

import { RULE5_REASON_REGISTRY_VERSION } from './version.js';

export const RULE5_OD014_REASON_CODES = [
  'R5_ADVERSE_EVENT_INTAKE_RECORDED',
  'R5_ADVERSE_EVENT_DATA_INCOMPLETE',
  'R5_SERIOUS_ADVERSE_EVENT_SUSPECTED',
  'R5_SEVERE_REACTION_SUSPECTED',
  'R5_CAUSALITY_NOT_ASSESSED',
  'R5_EMERGENCY_EVALUATION_REQUIRED',
  'R5_ADVERSE_EVENT_FOLLOW_UP_REQUIRED',
  'R5_PRODUCT_QUALITY_ISSUE_SUSPECTED',
  'R5_DUPLICATE_EVENT_REPORT_DETECTED',
  'R5_REGULATORY_REPORTABILITY_REVIEW_REQUIRED',
  'R5_REPORT_SUBMISSION_FAILED',
  'R5_REQUIRED_MONITORING_DATA_MISSING',
] as const;

export const RULE5_OD015_REASON_CODES = [
  'R5_EVIDENCE_MISSING_OR_UNVERIFIED',
  'R5_FOLLOW_UP_DATA_STALE',
  'R5_FOLLOW_UP_DATA_CONTRADICTORY',
  'R5_FOLLOW_UP_OVERDUE',
  'R5_UNKNOWN_SEVERITY',
  'R5_ACTIVE_ORAL_COUNT_BELOW_REQUIRED',
  'R5_REPLACEMENT_CLINICAL_EVIDENCE_INSUFFICIENT',
  'R5_DOSAGE_EVIDENCE_MISSING_OR_UNVERIFIED',
  'R5_MATERIAL_SAFETY_EVENT_REQUIRES_FULL_PLAN_REVALIDATION',
] as const;

export const RULE5_CLINICAL_REASON_CODES = [
  ...RULE5_OD014_REASON_CODES,
  ...RULE5_OD015_REASON_CODES,
] as const;

export type Rule5ClinicalReasonCode = (typeof RULE5_CLINICAL_REASON_CODES)[number];

export const RULE5_KNOWN_CLINICAL_REASON_CODE_SET: ReadonlySet<string> = new Set(
  RULE5_CLINICAL_REASON_CODES,
);

export type Rule5ClinicalReasonRegistryEntry = {
  code: Rule5ClinicalReasonCode;
  namespace: 'R5';
  meaning: string;
  executable: false;
  introducedInVersion: typeof RULE5_REASON_REGISTRY_VERSION;
  ownerDecisionAnchor: 'OD-R5-M0-014' | 'OD-R5-M0-015';
};

export type Rule5ClinicalReasonRegistry = {
  registryVersion: typeof RULE5_REASON_REGISTRY_VERSION;
  entries: readonly Rule5ClinicalReasonRegistryEntry[];
};
