from __future__ import annotations

RULE4_Q7BF_MANDATORY_GATE_IDS: tuple[str, ...] = (
    "Q7BF_RULE3_TARGET_RESOLVED",
    "Q7BF_FORMULA_SPECIFIC_PATHOLOGY",
    "Q7BF_POSITIVE_DISEASE_POLARITY",
    "Q7BF_NEGATIVE_THERAPEUTIC_POLARITY",
    "Q7BF_ACUTE_PHASE",
    "Q7BF_CLOSE_D04_USABLE_EVIDENCE",
    "Q7BF_STRICT_FORMULA_ISOLATION",
    "Q7BF_NO_GLOBAL_EVIDENCE_LEAKAGE",
)

RULE4_Q7BF_MANDATORY_GATE_ID_SET = frozenset(RULE4_Q7BF_MANDATORY_GATE_IDS)
