export {
  RULE1_BP_LYMPHATIC_SUPPORT,
  RULE1_BP_LYMPHATIC_SYSTOLIC_MAX_EXCLUSIVE,
  RULE1_BP_SANGUINE_SUPPORT,
  RULE1_BP_SANGUINE_SYSTOLIC_MIN,
  RULE1_EVIDENCE_ENTRY_KEY_ORDER,
  RULE1_EVIDENCE_KINDS,
  RULE1_FAILURE_CODES,
  RULE1_INPUT_KEY_ORDER,
  RULE1_LIFECYCLE_CLASSES,
  RULE1_OUTCOMES,
  RULE1_OUTPUT_KEY_ORDER,
  RULE1_PRODUCTION_MAPPING_REGISTRY,
  RULE1_REASON_CODES,
  RULE1_RESOLUTION_STATES,
  RULE1_RULE8_COMPARISON_STATES,
  RULE1_SYNTHETIC_TEST_CLASSIFICATION,
  RULE1_TEMPERAMENT_TOKENS,
} from './constants.js';
export type {
  Rule1EvidenceKind,
  Rule1FailureCode,
  Rule1LifecycleClass,
  Rule1Outcome,
  Rule1ResolutionState,
  Rule1Rule8ComparisonState,
  Rule1TemperamentToken,
} from './constants.js';
export { Rule1EvaluationError } from './errors.js';
export { evaluateRule1Shadow } from './evaluate.js';
export type {
  Rule1BloodLymphAxisContext,
  Rule1BloodPressureEvidence,
  Rule1CaseTemperamentEvidenceRegistry,
  Rule1DoctorSuppliedEvidenceItem,
  Rule1DoshaMapping,
  Rule1EvidenceDataVersions,
  Rule1Input,
  Rule1Output,
  Rule1PhotoEvidenceRef,
  Rule1StatusRef,
  Rule1TemperamentEvidenceEntry,
  Rule1UpstreamApplicability,
} from './types.js';
export {
  RULE1_CONTRACT_DOCUMENT_VERSION,
  RULE1_DISPLAY_TITLE,
  RULE1_INPUT_CONTRACT_VERSION,
  RULE1_NOT_CLINICALLY_ACTIVATED_PRESCRIPTION,
  RULE1_ORCHESTRATION_STATUS,
  RULE1_OUTPUT_CONTRACT_VERSION,
  RULE1_PRESCRIPTION_EFFECT,
  RULE1_RULE_IDENTITY,
  RULE1_RULE_NUMBER,
  RULE1_RUNTIME_STATUS,
} from './version.js';
