export {
  F3A_EXTRACTION_CANDIDATE_FOUNDATION,
  F3B_OPEN_SOURCE_OCR_ADAPTER_FOUNDATION,
  F3C_CANDIDATE_REVIEW_FOUNDATION,
  EVIDENCE_EXTRACT_PRODUCTION,
  EVIDENCE_OCR_ADAPTER_CONNECTED,
  SOURCE_TEXT_AUTHORITY_SCOPE,
  SOURCE_TEXT_REVIEW_DOES_NOT_AUTHORIZE,
  CONTENT_INTENTS,
  CANDIDATE_TYPES,
  CANDIDATE_STATUSES,
  VERIFICATION_POSTURE_F3A,
  EXTRACTION_METHODS,
  LIMITATION_CODES,
  SCRIPT_HINTS,
  MAX_EXTRACT_PAGES,
  MAX_EXTRACT_CANDIDATES,
  MAX_RAW_CHARS,
  MAX_NORMALIZED_CHARS,
  MAX_UNIT_CHARS,
  MAX_RANGE_CHARS,
  MAX_HEADING_CHARS,
  EXTRACT_TIMEOUT_MS,
  EXTRACT_JOB_TIMEOUT_MS,
  EXTRACT_PAGE_OCR_TIMEOUT_MS,
  MAX_CANDIDATES_PER_EVIDENCE,
  MAX_EXTRACTION_RUNS_PER_EVIDENCE,
  MAGIC_PREFIX_MAX,
  RETENTION_JOB_TYPES,
  EXTRACT_JOB_TYPE,
  CANDIDATE_SELECTOR_FORBIDDEN_FIELD_NAMES,
  CANDIDATE_REVIEW_ACTIONS,
  CANDIDATE_REVIEW_REASON_CODES,
  CANDIDATE_REVIEW_DECISION_STATUSES,
  CANDIDATE_REVIEW_REASON_BY_ACTION,
} from './types.js';
export type {
  CandidateType,
  CandidateStatus,
  ExtractionMethod,
  LimitationCode,
  ContentIntent,
  ScriptHint,
  SourceLocator,
  ExtractionCandidateDto,
  CandidateReviewAction,
  CandidateReviewReasonCode,
  CandidateReviewDecisionStatus,
  CandidateReviewEventDto,
  SourceLinkedCandidateView,
  ExtractionRequest,
  ExtractionResult,
  ExtractionSuccess,
  ExtractionRefusal,
  ExtractionProvider,
  EvidenceJobType,
} from './types.js';
export {
  F3D_FACT_CANDIDATE_FOUNDATION,
  FACT_CANDIDATE_CHANNELS,
  FACT_CANDIDATE_CATEGORIES,
  FACT_CANDIDATE_SOURCE_FIELDS,
  FACT_CANDIDATE_AUTHORITY_STATUSES,
  FACT_CANDIDATE_F3D1_AUTHORITY,
  FACT_CANDIDATE_DECISION_STATUSES,
  FACT_UNIT_POSTURES,
  FACT_NORMALIZATION_METHOD_F3D1,
  FACT_NORMALIZATION_VERSION_F3D1,
  FACT_NORMALIZATION_FINGERPRINT_F3D1,
  FACT_LIMITATION_CODES,
  FACT_SELECTOR_FORBIDDEN_FIELD_NAMES,
} from './factCandidateTypes.js';
export type {
  FactCandidateChannel,
  FactCandidateCategory,
  FactCandidateSourceField,
  FactCandidateAuthorityStatus,
  FactCandidateDecisionStatus,
  FactUnitPosture,
  FactLimitationCode,
  FactCandidateDto,
} from './factCandidateTypes.js';
export {
  F3D2D_FACT_NORMALIZATION_FOUNDATION,
  F3D2D_NORMALIZER_CONNECTED,
  F3D2D_PRODUCTION_ENABLED,
  FACT_NORMALIZATION_AUTHORITY_SCOPE,
  FACT_NORMALIZATION_KINDS,
  FACT_NORMALIZATION_NEGATION_SCOPE,
  FACT_NORMALIZATION_METHODS,
  FACT_NORMALIZATION_DECISION_STATUSES,
  FACT_NORMALIZATION_LIMITATION_CODES,
  F3D2D_PARENT_FACT_SUPERSEDE_PROPAGATES_NORMALIZATIONS,
  F3D2D_CUE_MATCH_ROWS_PERSISTED,
  FACT_NORMALIZATION_SELECTOR_FORBIDDEN_FIELD_NAMES,
} from './factNormalizationTypes.js';
export type {
  FactNormalizationKind,
  FactNormalizationMethod,
  FactNormalizationDecisionStatus,
  FactNormalizationLimitationCode,
  FactNormalizationDto,
} from './factNormalizationTypes.js';
export {
  FACT_VERIFICATION_AUTHORITY_SCOPE,
  FACT_VERIFICATION_ACTIONS,
  FACT_VERIFICATION_REASON_CODES,
  FACT_VERIFICATION_ACTION_REASON_CODES,
  MAX_FACT_VERIFICATION_SNAPSHOT_NORMS,
} from './factVerificationTypes.js';
export type {
  FactVerificationAction,
  FactVerificationReasonCode,
  FactVerificationDecisionStatus,
  FactVerificationEventDto,
  FactVerificationNormalizationDto,
} from './factVerificationTypes.js';
export {
  FACT_ANALYSIS_ACCEPTANCE_ACTION,
  FACT_ANALYSIS_ACCEPTANCE_AUTHORITY,
  FACT_ANALYSIS_ACCEPTANCE_REASON,
  FACT_ANALYSIS_ACCEPTANCE_CONTRACT_VERSION,
  MAX_FACT_ANALYSIS_ACCEPTANCE_SNAPSHOT_NORMS,
} from './factAnalysisAcceptanceTypes.js';
export type {
  FactAnalysisAcceptanceDecisionStatus,
  FactAnalysisAcceptanceEventDto,
  FactAnalysisAcceptanceNormalizationDto,
} from './factAnalysisAcceptanceTypes.js';
export {
  sha256Hex,
  extractorFingerprint,
  contentAwareExtractorFingerprint,
  candidateContentFingerprint,
  assertNoStorageInLocator,
} from './fingerprint.js';
export {
  detectScriptHint,
  boundRawText,
  normalizeCandidateText,
  boundUnit,
  boundRange,
} from './normalize.js';
export {
  extractJobsEnabled,
  extractOcrJobsEnabled,
  claimableEvidenceJobTypes,
  candidateReviewEnabled,
  factCandidatesEnabled,
} from './flags.js';
export { presentSourceLocator, bboxToCssPercent } from './reviewPresentation.js';
export {
  DeterministicFakeExtractor,
  NeverSettlingExtractor,
  defaultDeterministicExtractor,
} from './fakeExtractor.js';
export {
  F3D2_TERMINOLOGY_PACK_FOUNDATION,
  EMPTY_PACK_ENTRY_COUNT,
  PRODUCTION_TERMINOLOGY_PACK_PIN,
  INVALID_TERMINOLOGY_READINESS_POSTURE,
  NORMALIZATION_PARSER_AVAILABLE,
  CUE_PARSER_FOUNDATION,
  CUE_PARSER_CONNECTED,
  CUE_PARSER_PRODUCTION_ENABLED,
  CUE_PARSER_VERSION,
  CUE_PARSER_SOURCE_CHANNELS,
  CUE_PARSER_SOURCE_FIELDS,
  CUE_PARSER_SOURCE_COMBINATIONS,
  parseOwnerFrozenCues,
  TERMINOLOGY_SCHEMA_VERSION,
  TERMINOLOGY_CANONICALIZATION_VERSION,
  EMPTY_PACK_STATUS,
  EMPTY_PACK_APPROVAL_POSTURE,
  TERMINOLOGY_PACK_SELECTOR_FORBIDDEN_KEYS,
  TERMINOLOGY_SELECTOR_FORBIDDEN_FIELD_NAMES,
  TerminologyPackError,
  computeContentChecksum,
  canonicalChecksumJson,
  loadDefaultProductionPack,
  loadPinnedProductionPack,
  loadHistoricalEmptyPack,
  loadTerminologyPackFromFile,
  loadTerminologyPackFromObject,
  getTerminologyReadinessPosture,
  defaultProductionPackPath,
  pinnedProductionPackPath,
  historicalEmptyPackPath,
  syntheticFixturePackPath,
  bindOwnerApprovalToken,
  bindSyntheticTestToken,
  parseAndValidatePack,
  F3D2D2_DETERMINISTIC_NORMALIZER_FOUNDATION,
  F3D2D2_PERSISTENCE_CONNECTED,
  F3D2D2_PRODUCTION_WRITER_CONNECTED,
  FACT_NORMALIZER_METHOD,
  FACT_NORMALIZER_VERSION,
  NORMALIZER_CUE_SOURCE_COMBINATIONS,
  NORMALIZER_STRUCTURED_VITAL_FIELDS,
  NORMALIZER_FAILURE_CODES,
  MAX_NORMALIZER_DRAFTS,
  normalizeSourceLinkedFact,
  computeNormalizerFingerprint,
} from './terminology/index.js';
export type {
  TerminologyPack,
  LoadedTerminologyPack,
  TerminologyLookupResult,
  TerminologyReadinessPosture,
  EligibleCueParserInput,
  TerminologyCueMatchCandidate,
  CueParserResult,
  FactNormalizationDraft,
  NormalizeSourceLinkedFactInput,
  NormalizeSourceLinkedFactResult,
  NormalizerFailureCode,
} from './terminology/index.js';
