export {
  F3A_EXTRACTION_CANDIDATE_FOUNDATION,
  F3B_OPEN_SOURCE_OCR_ADAPTER_FOUNDATION,
  F3C_CANDIDATE_REVIEW_FOUNDATION,
  EVIDENCE_EXTRACT_PRODUCTION,
  EVIDENCE_OCR_ADAPTER_CONNECTED,
  SOURCE_TEXT_AUTHORITY_SCOPE,
  SOURCE_TEXT_REVIEW_DOES_NOT_AUTHORIZE,
  CONTENT_INTENTS,
  CANDIDATE_TYPES,
  CANDIDATE_STATUSES,
  VERIFICATION_POSTURE_F3A,
  EXTRACTION_METHODS,
  LIMITATION_CODES,
  SCRIPT_HINTS,
  MAX_EXTRACT_PAGES,
  MAX_EXTRACT_CANDIDATES,
  MAX_RAW_CHARS,
  MAX_NORMALIZED_CHARS,
  MAX_UNIT_CHARS,
  MAX_RANGE_CHARS,
  MAX_HEADING_CHARS,
  EXTRACT_TIMEOUT_MS,
  EXTRACT_JOB_TIMEOUT_MS,
  EXTRACT_PAGE_OCR_TIMEOUT_MS,
  MAX_CANDIDATES_PER_EVIDENCE,
  MAX_EXTRACTION_RUNS_PER_EVIDENCE,
  MAGIC_PREFIX_MAX,
  RETENTION_JOB_TYPES,
  EXTRACT_JOB_TYPE,
  CANDIDATE_SELECTOR_FORBIDDEN_FIELD_NAMES,
  CANDIDATE_REVIEW_ACTIONS,
  CANDIDATE_REVIEW_REASON_CODES,
  CANDIDATE_REVIEW_DECISION_STATUSES,
  CANDIDATE_REVIEW_REASON_BY_ACTION,
} from './types.js';
export type {
  CandidateType,
  CandidateStatus,
  ExtractionMethod,
  LimitationCode,
  ContentIntent,
  ScriptHint,
  SourceLocator,
  ExtractionCandidateDto,
  CandidateReviewAction,
  CandidateReviewReasonCode,
  CandidateReviewDecisionStatus,
  CandidateReviewEventDto,
  SourceLinkedCandidateView,
  ExtractionRequest,
  ExtractionResult,
  ExtractionSuccess,
  ExtractionRefusal,
  ExtractionProvider,
  EvidenceJobType,
} from './types.js';
export {
  F3D_FACT_CANDIDATE_FOUNDATION,
  FACT_CANDIDATE_CHANNELS,
  FACT_CANDIDATE_CATEGORIES,
  FACT_CANDIDATE_SOURCE_FIELDS,
  FACT_CANDIDATE_AUTHORITY_STATUSES,
  FACT_CANDIDATE_F3D1_AUTHORITY,
  FACT_CANDIDATE_DECISION_STATUSES,
  FACT_UNIT_POSTURES,
  FACT_NORMALIZATION_METHOD_F3D1,
  FACT_NORMALIZATION_VERSION_F3D1,
  FACT_NORMALIZATION_FINGERPRINT_F3D1,
  FACT_LIMITATION_CODES,
  FACT_SELECTOR_FORBIDDEN_FIELD_NAMES,
} from './factCandidateTypes.js';
export type {
  FactCandidateChannel,
  FactCandidateCategory,
  FactCandidateSourceField,
  FactCandidateAuthorityStatus,
  FactCandidateDecisionStatus,
  FactUnitPosture,
  FactLimitationCode,
  FactCandidateDto,
} from './factCandidateTypes.js';
export {
  sha256Hex,
  extractorFingerprint,
  contentAwareExtractorFingerprint,
  candidateContentFingerprint,
  assertNoStorageInLocator,
} from './fingerprint.js';
export {
  detectScriptHint,
  boundRawText,
  normalizeCandidateText,
  boundUnit,
  boundRange,
} from './normalize.js';
export {
  extractJobsEnabled,
  extractOcrJobsEnabled,
  claimableEvidenceJobTypes,
  candidateReviewEnabled,
  factCandidatesEnabled,
} from './flags.js';
export { presentSourceLocator, bboxToCssPercent } from './reviewPresentation.js';
export {
  DeterministicFakeExtractor,
  NeverSettlingExtractor,
  defaultDeterministicExtractor,
} from './fakeExtractor.js';
export {
  F3D2_TERMINOLOGY_PACK_FOUNDATION,
  EMPTY_PACK_ENTRY_COUNT,
  PRODUCTION_TERMINOLOGY_PACK_PIN,
  INVALID_TERMINOLOGY_READINESS_POSTURE,
  NORMALIZATION_PARSER_AVAILABLE,
  TERMINOLOGY_SCHEMA_VERSION,
  EMPTY_PACK_STATUS,
  EMPTY_PACK_APPROVAL_POSTURE,
  TERMINOLOGY_PACK_SELECTOR_FORBIDDEN_KEYS,
  TERMINOLOGY_SELECTOR_FORBIDDEN_FIELD_NAMES,
  TerminologyPackError,
  computeContentChecksum,
  canonicalChecksumJson,
  loadDefaultProductionPack,
  loadPinnedProductionPack,
  loadHistoricalEmptyPack,
  loadTerminologyPackFromFile,
  loadTerminologyPackFromObject,
  getTerminologyReadinessPosture,
  defaultProductionPackPath,
  pinnedProductionPackPath,
  historicalEmptyPackPath,
  syntheticFixturePackPath,
  bindOwnerApprovalToken,
  bindSyntheticTestToken,
  parseAndValidatePack,
} from './terminology/index.js';
export type {
  TerminologyPack,
  LoadedTerminologyPack,
  TerminologyLookupResult,
  TerminologyReadinessPosture,
} from './terminology/index.js';
