import type { ReactNode } from 'react';
import {
  DEMO_CLINICAL_BANNER,
  type ClinicalResultDisplay,
  type ElectricityStatus,
  type MedicineToken as MedicineTokenType,
} from '../../lib/clinicalDisplay/types';
import { PreviewModeBanner } from '../entry/PreviewModeBanner';
import { Surface } from '../ui/Primitives';

export function DemoClinicalBanner({ message = DEMO_CLINICAL_BANNER }: { message?: string }) {
  return <PreviewModeBanner message={message} />;
}

export function NotGeneratedState({ reason }: { reason: string }) {
  return (
    <div className="ehas2-not-generated" role="status">
      <strong>Not generated by clinical engine</strong>
      <p>{reason}</p>
    </div>
  );
}

export function EngineVersionBadge({ result }: { result: ClinicalResultDisplay }) {
  return (
    <ul className="ehas2-version-badges" aria-label="Engine and data versions">
      <li>Engine: {result.engineVersion}</li>
      <li>Rules: {result.ruleVersion}</li>
      <li>Disease data: {result.diseaseDataVersion}</li>
      <li>Medicine data: {result.medicineDataVersion}</li>
      <li>Contract: {result.contractVersion}</li>
    </ul>
  );
}

export function ClinicalResultHeader({ result }: { result: ClinicalResultDisplay }) {
  return (
    <header className="ehas2-clinical-header">
      <DemoClinicalBanner />
      <h1>Prescription layout</h1>
      <p>
        {result.patientContext.displayName} · {result.patientContext.ageYears}y ·{' '}
        {result.patientContext.gender}
      </p>
      <p>
        Case {result.caseContext.casePreviewId} · Phase {result.caseContext.phase} · Severity{' '}
        {result.caseContext.severity}
      </p>
      <p>Chief complaint: {result.caseContext.chiefComplaint}</p>
      <EngineVersionBadge result={result} />
    </header>
  );
}

export function SystemBadgeGroup({
  systems,
  primary,
}: {
  systems: string[];
  primary: string | null;
}) {
  if (systems.length === 0) return <NotGeneratedState reason="No affected systems in result." />;
  return (
    <ul className="ehas2-chip-row" aria-label="Affected systems">
      {systems.map((s) => (
        <li key={s} className="ehas2-chip">
          {s}
          {primary === s ? ' (primary)' : ''}
        </li>
      ))}
    </ul>
  );
}

export function PolarityCard({ polarity }: { polarity: string | null }) {
  return (
    <Surface>
      <h3>Polarity</h3>
      <p>{polarity ?? 'Not generated by clinical engine'}</p>
      <p className="ehas2-field__hint">Status text included — not color-only.</p>
    </Surface>
  );
}

export function MedicineToken({ medicine }: { medicine: MedicineTokenType }) {
  return (
    <span className="ehas2-medicine-token">
      <strong>{medicine.displayName}</strong> <code>{medicine.code}</code>
    </span>
  );
}

export function PotencyBadge({ potency }: { potency: string | null }) {
  return <span className="ehas2-badge">{potency ?? 'Not generated by clinical engine'}</span>;
}

export function ElectricityStatusView({ electricity }: { electricity: ElectricityStatus }) {
  if (electricity.state === 'resolved') {
    return <p>Electricity: {electricity.value}</p>;
  }
  return (
    <p role="status">
      Electricity {electricity.state}: {electricity.reason}
    </p>
  );
}

export function SafetyWarning({ warnings }: { warnings: string[] }) {
  if (!warnings.length) return null;
  return (
    <div className="ehas2-emergency" role="alert">
      <h3>Safety warnings</h3>
      <ul>
        {warnings.map((w) => (
          <li key={w}>{w}</li>
        ))}
      </ul>
    </div>
  );
}

export function EvidencePanel({ notes }: { notes: string[] }) {
  if (!notes.length) return <NotGeneratedState reason="No evidence notes supplied." />;
  return (
    <Surface>
      <h3>Evidence</h3>
      <ul>
        {notes.map((n) => (
          <li key={n}>{n}</li>
        ))}
      </ul>
    </Surface>
  );
}

export function ClinicalSummarySection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="ehas2-surface ehas2-summary-section">
      <h2>{title}</h2>
      {children}
    </section>
  );
}
