import type {
  ClinicalResultDisplay,
  ExternalApplicationDisplay,
  OralMixtureDisplay,
  TabletSectionADisplay,
  TabletSlotDisplay,
} from '../../lib/clinicalDisplay/types';
import { Surface } from '../ui/Primitives';
import {
  ElectricityStatusView,
  MedicineToken,
  NotGeneratedState,
  PotencyBadge,
} from './ClinicalPrimitives';

export function OralFormulaCard({ mixture }: { mixture: OralMixtureDisplay }) {
  return (
    <article className="ehas2-formula-card">
      <header>
        <h3>{mixture.label}</h3>
        <p>Target: {mixture.clinicalTarget}</p>
      </header>
      <ul className="ehas2-medicine-list">
        {mixture.medicines.map((m) => (
          <li key={m.code}>
            <MedicineToken medicine={m} />
          </li>
        ))}
      </ul>
      <p>
        Potency: <PotencyBadge potency={mixture.potency} />
      </p>
      <p>Dose / instructions: {mixture.doseInstructions ?? 'Not generated by clinical engine'}</p>
      <ElectricityStatusView electricity={mixture.electricity} />
      <p>Evidence: {mixture.evidence}</p>
      <p className="ehas2-field__hint">Source version: {mixture.sourceVersion}</p>
      {mixture.noRepetitionWarning ? <p role="status">{mixture.noRepetitionWarning}</p> : null}
    </article>
  );
}

export function OralMixturesSection({ mixtures }: { mixtures: OralMixtureDisplay[] }) {
  if (mixtures.length === 0) {
    return <NotGeneratedState reason="No oral mixtures in this result." />;
  }
  return (
    <div className={`ehas2-formula-grid ehas2-formula-grid--${mixtures.length}`}>
      {mixtures.map((m) => (
        <OralFormulaCard key={m.id} mixture={m} />
      ))}
    </div>
  );
}

export function TabletSectionA({ section }: { section: TabletSectionADisplay }) {
  if (section.status === 'not-generated') {
    return (
      <NotGeneratedState
        reason={section.notGeneratedReason ?? 'Not generated by clinical engine'}
      />
    );
  }
  return (
    <Surface>
      <h3>Tablet Section A</h3>
      {section.demoIndependentSelectionLabel ? (
        <p className="ehas2-preview-banner" role="status">
          ◇ {section.demoIndependentSelectionLabel}
        </p>
      ) : null}
      <ul className="ehas2-medicine-list">
        {section.medicines.map((m) => (
          <li key={m.code}>
            <MedicineToken medicine={m} />
          </li>
        ))}
      </ul>
      <p>Target: {section.clinicalTarget ?? 'Not generated by clinical engine'}</p>
      <p>Evidence: {section.evidence ?? 'Not generated by clinical engine'}</p>
      <p>
        Potency: <PotencyBadge potency={section.potency} />
      </p>
      {section.electricity ? <ElectricityStatusView electricity={section.electricity} /> : null}
      <p>Schedule: {section.scheduleInstructions ?? 'Not generated by clinical engine'}</p>
      <p className="ehas2-field__hint">Selection source: {section.selectionSource ?? '—'}</p>
      <p className="ehas2-field__hint">Oral overlap: {section.oralOverlapMetadata ?? '—'}</p>
    </Surface>
  );
}

export function TabletScheduleSlot({ slot }: { slot: TabletSlotDisplay }) {
  const title =
    slot.slotId === 'before-food'
      ? 'Before Food'
      : slot.slotId === 'after-food'
        ? 'After Food'
        : 'Night';
  if (slot.status === 'not-generated') {
    return (
      <article className="ehas2-slot-card">
        <h4>{title}</h4>
        <NotGeneratedState reason={slot.reason} />
      </article>
    );
  }
  return (
    <article className="ehas2-slot-card">
      <h4>{title}</h4>
      <MedicineToken medicine={slot.medicine} />
      <p>Target: {slot.clinicalTarget}</p>
      <p>Evidence: {slot.evidence}</p>
      <p>Timing: {slot.timing}</p>
      <p>
        Potency: <PotencyBadge potency={slot.potency} />
      </p>
      {slot.electricity ? <ElectricityStatusView electricity={slot.electricity} /> : null}
    </article>
  );
}

export function TabletSectionB({ slots }: { slots: TabletSlotDisplay[] }) {
  return (
    <div className="ehas2-slot-grid">
      {slots.map((slot) => (
        <TabletScheduleSlot key={slot.slotId} slot={slot} />
      ))}
    </div>
  );
}

export function ExternalApplicationCard({ item }: { item: ExternalApplicationDisplay }) {
  return (
    <article className="ehas2-formula-card">
      <h3>{item.stageRouteLabel}</h3>
      <p>Body site: {item.bodySite}</p>
      <p>Target: {item.clinicalTarget}</p>
      <ul className="ehas2-medicine-list">
        {item.medicines.map((m) => (
          <li key={m.code}>
            <MedicineToken medicine={m} />
          </li>
        ))}
      </ul>
      <p>Preparation: {item.preparation}</p>
      <p>
        Frequency: {item.frequency} · Duration: {item.duration}
      </p>
      <p>
        Potency: <PotencyBadge potency={item.potency} />
      </p>
      {item.electricity ? <ElectricityStatusView electricity={item.electricity} /> : null}
      <p>Evidence: {item.evidence}</p>
      <p>Safety: {item.safetyInstructions}</p>
      {item.notClinicallyIndicatedReason ? (
        <p role="status">{item.notClinicallyIndicatedReason}</p>
      ) : null}
    </article>
  );
}

export function ExternalApplicationsSection({ items }: { items: ExternalApplicationDisplay[] }) {
  if (items.length === 0) {
    return <NotGeneratedState reason="No external application indicated in this result." />;
  }
  return (
    <div className={`ehas2-formula-grid ehas2-formula-grid--ext-${items.length}`}>
      {items.map((item) => (
        <ExternalApplicationCard key={item.id} item={item} />
      ))}
    </div>
  );
}

export function DailySchedule({ result }: { result: ClinicalResultDisplay }) {
  if (result.dailySchedule.length === 0) {
    return <NotGeneratedState reason="No daily schedule instructions supplied." />;
  }
  return (
    <Surface>
      <h3>Daily schedule</h3>
      {result.scheduleConflictWarning ? (
        <p className="ehas2-field__error" role="alert">
          {result.scheduleConflictWarning}
        </p>
      ) : null}
      <ol className="ehas2-schedule">
        {result.dailySchedule.map((block) => (
          <li key={block.blockId}>
            <strong>{block.label}</strong>
            <ul>
              {block.instructions.map((line) => (
                <li key={line}>{line}</li>
              ))}
            </ul>
          </li>
        ))}
      </ol>
    </Surface>
  );
}
