'use client';

import { useId, useState } from 'react';
import type {
  ClinicalResultDisplay,
  ClinicalStageDisplay,
  ClinicianReviewStatus,
  ReportFindingDisplay,
} from '../../lib/clinicalDisplay/types';
import { Button } from '../ui/Button';
import { Surface } from '../ui/Primitives';
import {
  ClinicalSummarySection,
  NotGeneratedState,
  PolarityCard,
  SystemBadgeGroup,
} from './ClinicalPrimitives';
import {
  DailySchedule,
  ExternalApplicationsSection,
  OralMixturesSection,
  TabletSectionA,
  TabletSectionB,
} from './PrescriptionSections';

export function ReportFindingsSection({ findings }: { findings: ReportFindingDisplay[] }) {
  if (!findings.length) {
    return <NotGeneratedState reason="No structured report findings in this result." />;
  }
  return (
    <ul className="ehas2-findings">
      {findings.map((f) => (
        <li key={f.id}>
          <Surface>
            <h3>
              {f.findingLabel} <span className="ehas2-badge">SYNTHETIC</span>
            </h3>
            <p>
              {f.reportType} · {f.valueStatus}
            </p>
            <p>Source: {f.sourceDocumentLabel}</p>
            <p>Confidence: {f.confidenceStatus}</p>
            <p>Relevance: {f.clinicalRelevance}</p>
          </Surface>
        </li>
      ))}
    </ul>
  );
}

export function ClinicalStageCard({ stage }: { stage: ClinicalStageDisplay }) {
  const panelId = useId();
  const [open, setOpen] = useState(false);
  return (
    <article className="ehas2-stage-card">
      <h3>
        <button
          type="button"
          className="ehas2-timeline__toggle"
          aria-expanded={open}
          aria-controls={panelId}
          onClick={() => setOpen((v) => !v)}
        >
          Stage {stage.stage}: {stage.title}
        </button>
      </h3>
      {open ? (
        <div id={panelId} className="ehas2-stage-body">
          <p>
            <strong>Purpose:</strong> {stage.clinicalPurpose}
          </p>
          <p>
            <strong>Findings:</strong> {stage.findings}
          </p>
          <p>
            <strong>Mechanism:</strong> {stage.mechanism}
          </p>
          <p>
            <strong>Expected progression:</strong> {stage.expectedProgression}
          </p>
          <p>
            <strong>Monitoring:</strong> {stage.monitoring}
          </p>
          <p>
            <strong>Warnings:</strong> {stage.warnings}
          </p>
          <p className="ehas2-field__hint">Evidence source: {stage.evidenceSource}</p>
        </div>
      ) : null}
    </article>
  );
}

export function ClinicalStagesSection({ stages }: { stages: ClinicalStageDisplay[] }) {
  if (!stages.length) {
    return <NotGeneratedState reason="Stage 2–6 content not generated." />;
  }
  return (
    <div className="ehas2-stack">
      {stages.map((s) => (
        <ClinicalStageCard key={s.stage} stage={s} />
      ))}
    </div>
  );
}

const SUMMARY_ORDER = [
  'Patient and Case Overview',
  'Uploaded Report Findings',
  'Clinical Assessment',
  'EH Interpretation',
  'Root Cause and Systems',
  'Oral Prescription',
  'Tablet Section A',
  'Tablet Section B',
  'External Application',
  'Diet and Guidance',
  'Safety and Follow-up',
  'Stage 2–6 Clinical Explanation',
  'Engine/Data Version and Evidence',
] as const;

export function ClinicalSummaryView({ result }: { result: ClinicalResultDisplay }) {
  return (
    <div className="ehas2-stack" data-summary-order={SUMMARY_ORDER.join('|')}>
      <ClinicalSummarySection title="Patient and Case Overview">
        <p>
          {result.patientContext.displayName} · Case {result.caseContext.casePreviewId}
        </p>
        <p>
          Phase {result.caseContext.phase} · Severity {result.caseContext.severity}
        </p>
        <p>
          Symptoms: {result.normalizedSymptoms.join('; ') || 'Not generated by clinical engine'}
        </p>
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Uploaded Report Findings">
        <ReportFindingsSection findings={result.reportFindings} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Clinical Assessment">
        <p>Diseases: {result.detectedDiseases.join(', ') || 'Not generated by clinical engine'}</p>
        <p>Temperament: {result.temperament ?? 'Not generated by clinical engine'}</p>
        <p>Constitution: {result.constitution ?? 'Not generated by clinical engine'}</p>
      </ClinicalSummarySection>
      <ClinicalSummarySection title="EH Interpretation">
        <PolarityCard polarity={result.polarity} />
        <p>Clinical target: {result.clinicalTarget ?? 'Not generated by clinical engine'}</p>
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Root Cause and Systems">
        <p>{result.rootCause ?? 'Not generated by clinical engine'}</p>
        <SystemBadgeGroup systems={result.affectedSystems} primary={result.primarySystem} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Oral Prescription">
        <OralMixturesSection mixtures={result.oralMixtures} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Tablet Section A">
        <TabletSectionA section={result.tabletSectionA} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Tablet Section B">
        <TabletSectionB slots={result.tabletSectionB} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="External Application">
        <ExternalApplicationsSection items={result.externalApplications} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Diet and Guidance">
        {result.dietGuidance.length ? (
          <ul>
            {result.dietGuidance.map((d) => (
              <li key={d}>{d}</li>
            ))}
          </ul>
        ) : (
          <NotGeneratedState reason="No diet/guidance supplied." />
        )}
        <DailySchedule result={result} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Safety and Follow-up">
        {result.safetyWarnings.length ? (
          <ul>
            {result.safetyWarnings.map((w) => (
              <li key={w}>{w}</li>
            ))}
          </ul>
        ) : (
          <NotGeneratedState reason="No safety warnings supplied." />
        )}
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Stage 2–6 Clinical Explanation">
        <ClinicalStagesSection stages={result.stages} />
      </ClinicalSummarySection>
      <ClinicalSummarySection title="Engine/Data Version and Evidence">
        <p>
          Engine {result.engineVersion} · Rules {result.ruleVersion} · Disease{' '}
          {result.diseaseDataVersion} · Medicine {result.medicineDataVersion}
        </p>
        <ul>
          {result.evidenceNotes.map((n) => (
            <li key={n}>{n}</li>
          ))}
        </ul>
      </ClinicalSummarySection>
    </div>
  );
}

export { SUMMARY_ORDER };

export function PrescriptionStatusBadge({ status }: { status: string }) {
  return <span className="ehas2-badge">{status}</span>;
}

export function ClinicianReviewPanel({ status }: { status: ClinicianReviewStatus }) {
  const [message, setMessage] = useState<string | undefined>();
  const [reason, setReason] = useState('');
  const [modifyOpen, setModifyOpen] = useState(false);

  function act(action: string) {
    setMessage(
      `Review service not connected. “${action}” was not persisted (UI preview only). Current status remains: ${status}.`,
    );
  }

  return (
    <Surface>
      <h3>Clinician review</h3>
      <p>
        Status: <PrescriptionStatusBadge status={status} />
      </p>
      <div className="ehas2-action-row">
        <Button type="button" variant="primary" onClick={() => act('Accept')}>
          Accept
        </Button>
        <Button type="button" variant="secondary" onClick={() => act('Request Clarification')}>
          Request Clarification
        </Button>
        <Button type="button" variant="secondary" onClick={() => setModifyOpen(true)}>
          Modify Draft
        </Button>
        <Button type="button" variant="ghost" onClick={() => act('Reject')}>
          Reject
        </Button>
      </div>
      {modifyOpen ? (
        <div className="ehas2-stack">
          <p role="status">
            Controlled-review placeholder — medicine cards are not edited here. Review service not
            connected.
          </p>
          <label htmlFor="review-reason">Reason (required for modify preview)</label>
          <textarea
            id="review-reason"
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            rows={3}
          />
          <Button
            type="button"
            variant="primary"
            disabled={!reason.trim()}
            onClick={() => {
              act('Modify Draft');
              setModifyOpen(false);
            }}
          >
            Submit modify preview
          </Button>
        </div>
      ) : null}
      {message ? (
        <p className="ehas2-field__error" role="alert">
          {message}
        </p>
      ) : null}
    </Surface>
  );
}
