/**
 * Local preview gallery catalog — static links only.
 * No Principal, TenantContext, session, OTP, engine, or DB writes.
 */

export type PreviewCatalogItem = {
  id: string;
  title: string;
  description: string;
  href: string;
  group:
    | 'entry'
    | 'doctor'
    | 'clinical'
    | 'formula'
    | 'profile'
    | 'management'
    | 'super-admin'
    | 'audit';
  shell: 'public' | 'doctor' | 'management' | 'super-admin' | 'fixture' | 'audit';
};

export const PREVIEW_CATALOG: readonly PreviewCatalogItem[] = [
  {
    id: 'splash',
    title: 'Splash',
    description: 'Brand splash — UI foundation',
    href: '/',
    group: 'entry',
    shell: 'public',
  },
  {
    id: 'login',
    title: 'Login',
    description: 'OTP_PROVIDER_NOT_CONFIGURED truthful stop',
    href: '/login',
    group: 'entry',
    shell: 'public',
  },
  {
    id: 'otp',
    title: 'OTP provider-not-configured',
    description: 'Verify OTP UI — no real OTP',
    href: '/verify-otp',
    group: 'entry',
    shell: 'public',
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Doctor dashboard shell',
    href: '/dashboard',
    group: 'doctor',
    shell: 'doctor',
  },
  {
    id: 'patients',
    title: 'Patient List',
    description: 'Synthetic patient list',
    href: '/patients',
    group: 'doctor',
    shell: 'doctor',
  },
  {
    id: 'patient-detail',
    title: 'Patient Detail',
    description: 'Demo Patient A detail',
    href: '/patients/syn-patient-001',
    group: 'doctor',
    shell: 'doctor',
  },
  {
    id: 'patient-history',
    title: 'Patient History',
    description: 'Synthetic history',
    href: '/patients/syn-patient-001/history',
    group: 'doctor',
    shell: 'doctor',
  },
  {
    id: 'new-case',
    title: 'New Case',
    description: 'Case intake UI',
    href: '/cases/new',
    group: 'clinical',
    shell: 'doctor',
  },
  {
    id: 'clinical-inputs',
    title: 'Clinical inputs',
    description: 'New case clinical fields',
    href: '/cases/new',
    group: 'clinical',
    shell: 'doctor',
  },
  {
    id: 'reports',
    title: 'Report selection UI',
    description: 'Report picker — upload not active',
    href: '/cases/new/reports',
    group: 'clinical',
    shell: 'doctor',
  },
  {
    id: 'case-review',
    title: 'Case Review',
    description: 'Pre-analysis review UI',
    href: '/cases/new/review',
    group: 'clinical',
    shell: 'doctor',
  },
  {
    id: 'analysis',
    title: 'Analysis NOT_CONNECTED',
    description: 'CLINICAL_ENGINE_NOT_CONNECTED',
    href: '/cases/preview-case-empty/analysis',
    group: 'clinical',
    shell: 'doctor',
  },
  {
    id: 'rx-3mix',
    title: 'Oral prescription · 3 mixtures',
    description: 'Synthetic layout fixture',
    href: '/cases/preview-case-3mix/prescription',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'rx-4mix',
    title: 'Oral prescription · 4 mixtures',
    description: 'Synthetic layout fixture',
    href: '/cases/preview-case-4mix/prescription',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'rx-5mix',
    title: 'Oral prescription · 5 mixtures',
    description: 'Synthetic layout fixture',
    href: '/cases/preview-case-5mix/prescription',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'tablet-a',
    title: 'Tablet Section A',
    description: 'Independent-selection layout fixture',
    href: '/cases/preview-case-3mix/prescription#tablet-section-a',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'tablet-b',
    title: 'Tablet Section B',
    description: 'Before/after/night slots fixture',
    href: '/cases/preview-case-4mix/prescription#tablet-section-b',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'ext-0',
    title: 'External applications · 0',
    description: 'Empty external layout',
    href: '/cases/preview-case-3mix/prescription#external-applications',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'ext-1',
    title: 'External applications · 1',
    description: 'One external fixture',
    href: '/cases/preview-case-ext-1/prescription#external-applications',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'ext-2',
    title: 'External applications · 2',
    description: 'Two external fixtures',
    href: '/cases/preview-case-4mix/prescription#external-applications',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'ext-3',
    title: 'External applications · 3',
    description: 'Three external fixtures',
    href: '/cases/preview-case-ext-3/prescription#external-applications',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'ext-4',
    title: 'External applications · 4',
    description: 'Four external fixtures',
    href: '/cases/preview-case-5mix/prescription#external-applications',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'summary',
    title: 'Clinical Summary',
    description: 'Synthetic summary layout',
    href: '/cases/preview-case-3mix/summary',
    group: 'clinical',
    shell: 'fixture',
  },
  {
    id: 'clinician-review',
    title: 'Clinician Review',
    description: 'Review UI — not saved',
    href: '/cases/preview-case-3mix/review',
    group: 'clinical',
    shell: 'fixture',
  },
  {
    id: 'rx-history',
    title: 'Prescription History',
    description: 'Synthetic history list',
    href: '/prescriptions',
    group: 'doctor',
    shell: 'doctor',
  },
  {
    id: 'print',
    title: 'Print Preview',
    description: 'Print layout with demo watermark',
    href: '/print/preview-case-3mix',
    group: 'formula',
    shell: 'fixture',
  },
  {
    id: 'profile',
    title: 'Doctor Profile',
    description: 'AUTH_NOT_CONNECTED profile shell',
    href: '/profile',
    group: 'profile',
    shell: 'doctor',
  },
  {
    id: 'qualifications',
    title: 'Qualifications',
    description: 'Profile qualifications UI',
    href: '/profile/qualifications',
    group: 'profile',
    shell: 'doctor',
  },
  {
    id: 'registrations',
    title: 'Registrations',
    description: 'Profile registrations UI',
    href: '/profile/registrations',
    group: 'profile',
    shell: 'doctor',
  },
  {
    id: 'clinic-settings',
    title: 'Clinic Settings',
    description: 'Clinic settings UI',
    href: '/clinic/settings',
    group: 'profile',
    shell: 'doctor',
  },
  {
    id: 'clinic-hours',
    title: 'Clinic Hours',
    description: 'Operating hours UI',
    href: '/clinic/hours',
    group: 'profile',
    shell: 'doctor',
  },
  {
    id: 'prescriber',
    title: 'Prescriber Identity Preview',
    description: 'Prescription identity snapshot UI',
    href: '/profile/prescriber-preview',
    group: 'profile',
    shell: 'doctor',
  },
  {
    id: 'feedback',
    title: 'Feedback & Support',
    description: 'Doctor feedback form',
    href: '/feedback',
    group: 'doctor',
    shell: 'doctor',
  },
  {
    id: 'management',
    title: 'Management Admin NOT_CONNECTED',
    description: 'Separate Management shell — not in DoctorShell',
    href: '/preview/management',
    group: 'management',
    shell: 'management',
  },
  {
    id: 'super-admin',
    title: 'Super Admin foundation status',
    description: 'Separate control-plane shell — not in DoctorShell',
    href: '/preview/super-admin',
    group: 'super-admin',
    shell: 'super-admin',
  },
  {
    id: 'clinical-integration-status',
    title: 'Clinical integration status (audit)',
    description: 'Phase 5A non-clinical AUDIT_ONLY / NOT_CONNECTED board',
    href: '/preview/clinical-integration-status',
    group: 'audit',
    shell: 'audit',
  },
  {
    id: 'clinical-validation',
    title: 'Clinical validation (Phase 5C)',
    description: 'Synthetic nine-rule orchestration board — prescription NOT_CONNECTED',
    href: '/preview/clinical-validation',
    group: 'audit',
    shell: 'audit',
  },
  {
    id: 'candidate-review',
    title: 'Source-linked candidate review (F3C)',
    description: 'Synthetic extraction-candidate review — transcription only, not clinical',
    href: '/preview/candidate-review',
    group: 'audit',
    shell: 'audit',
  },
] as const;

export const PREVIEW_GROUPS = [
  { id: 'entry', label: 'Entry' },
  { id: 'doctor', label: 'Doctor workspace' },
  { id: 'clinical', label: 'Clinical UX' },
  { id: 'formula', label: 'Formula layout fixtures' },
  { id: 'profile', label: 'Profile & clinic' },
  { id: 'management', label: 'Management Admin' },
  { id: 'super-admin', label: 'Super Admin' },
  { id: 'audit', label: 'Audit status' },
] as const;
